app_supplier:
    resource: |
        alias: app.supplier
        except: ['show']
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: app_admin_supplier
    type: sylius.resource
    prefix: /admin