    App\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addSupplierMenu }
            # - { name: kernel.event_listener, event: {Event iš MainMenuBuilder}, method: {Mūsų sukurtas metodas}}
